sudo: required
services: 
  - docker

before_install:
  - docker build -t nikolaytomitov/docker-react -f Dockerfile.dev .

script:
  - docker run nikolaytomitov/docker-react npm run test -- --coverage