sudo: required
services: 
  - docker

before_install:
  - docker build -t nikolaytomitov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikolaytomitov/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-993425271305"
  bucket_path: "Docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_ACCESS_KEY"